apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      nodePort: {{ .Values.minio.nodePortApi }}
    - name: console
      port: 9001
      nodePort: {{ .Values.minio.nodePortConsole }}
  type: NodePort
