apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: burakince/mlflow:latest
        command: ["/mlflow/.venv/bin/mlflow"]
        args:
          - "server"
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "5000"
          - "--backend-store-uri"
          - "postgresql://mlflow:mlflowpass@postgresql:5432/mlflowdb"
          - "--default-artifact-root"
          - "s3://mlflow"
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio:9000
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: BACKEND_STORE_URI
          value: postgresql://mlflow:mlflowpass@postgresql:5432/mlflowdb
        - name: ARTIFACT_ROOT
          value: s3://mlflow
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: mlflow-data
          mountPath: /mlflow/data
      volumes:
      - name: mlflow-data
        persistentVolumeClaim:
          claimName: mlflow-pvc
