apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
stringData:
  {{- if .Values.minio.generateCredentials }}
  {{- if not .Values.minio.accessKey }}
  AWS_ACCESS_KEY_ID: {{ randAlphaNum 16 | quote }}
  {{- else }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKey | quote }}
  {{- end }}
  {{- if not .Values.minio.secretKey }}
  AWS_SECRET_ACCESS_KEY: {{ randAlphaNum 32 | quote }}
  {{- else }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretKey | quote }}
  {{- end }}
  {{- else }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretKey | quote }}
  {{- end }}
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
